<?php

namespace GameBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PlayerRoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRoomRepository extends EntityRepository
{
}