<?php

namespace GameBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends EntityRepository
{
    /* Get players order by wins
     *
     * @return Array
     */
    public function findAllOrderByWins()
    {
        $qb = $this
                ->createQueryBuilder('p')
                ->select(array('p'))
                ->orderBy('p.wins', 'DESC');

        return $qb->getQuery()->execute();
    }
}