<?php

namespace GameBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomRepository extends EntityRepository
{
    /**
      * Get all active rooms
      * @return Array of rooms
     **/
    public function getAllActive()
    {
        $qb = $this->createQueryBuilder('r');

        $qb->select(array('r'))->where('r.done = 0');

        return $qb->getQuery()->execute();
    }
}